### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [fanjos333/Jammming#4]
All in all, you did an awesome job on your project. You hit all the major points and created everything needed. Great job figuring out the Spotify.js file. Also, you demonstrated a clear understanding of the React fundamentals. Great job not mutating state, passing props, rendering children, updating state and more. One thing you can work on is your indentation. It's really important that your indentation is clean on every file. Great job on this project and keep up the great work!

**Comment by fanjos333** [comment]
Thank you very much!
